### ISSUE TITLE
Broken Url fmhy.pages.dev [BUG]

### ISSUE THREAD

**Issue by mehapps** [fmhy/FMHYFilterlist#19]
**Describe the bug**
Unsure if this is really a bug or not, but shouldn't fmhy.pages.dev be marked as safe? currently no data on it. 

**Broken Url(s)/Feature**
fmhy.pages.dev

**Additional context**
Using the FMHY Safeguard extension

**Comment by MIOGMIOG** [comment]
This was fixed in https://github.com/kenhendricks00/FMHY-SafeGuard/commit/977306bcc996b373857fbb68b64d09eae3e78a0d
Also this is the wrong github repo to report this issue. (Older versions of the extension had this github repo linked for reporting issues, this should be fixed now in newer versions of the extension)
Thanks anyway
