### ISSUE TITLE
Broken Url https://mkvcinemas.app  [BUG]

### ISSUE THREAD

**Issue by hc27795** [fmhy/FMHYFilterlist#20]
**Describe the bug**
Extension say" No data available". However I know mkv cinemas should be in filterlist.I think mkv cinemas link got changed recently. Pls update

**Broken Url(s)/Feature**
https://mkvcinemas.app/

**Additional context**
Not applicable

**Comment by MIOGMIOG** [comment]
Hi, this is the wrong github repo to report FMHY SafeGuard issues (this is not really your fault, the extension had FMHYFilterlist issues linked under the "Let us know" link, but this was fixed in the 1.1.1 version of the extension)
The right place to report FMHY SafeGuard issues should be https://github.com/kenhendricks00/FMHY-SafeGuard/issues
We're really sorry for this confusion, but thanks for the report anyway!
